<script lang="ts" setup>
const props = defineProps<{
  /** Slug generated by @nuxt/content */
  id?: string;
}>();

const BADGE_BY_GROUP: Record<string, string> = {
  added: "badge-success",
  changed: "badge-info",
  deprecated: "badge-warning",
  fixed: "badge-warning",
  removed: "badge-error",
  security: "badge-error",
};

const badgeClass = computed(() =>
  BADGE_BY_GROUP[props.id?.replace(/-\d+$/, "") ?? ""] ?? "badge-neutral",
);
</script>

<template>
  <!-- CHANGELOG "GROUP" BADGES (derived from H3s in Markdown) -->
  <h3 :id class="my-4">
    <span class="badge badge-soft font-mono font-semibold uppercase" :class="badgeClass">
      <slot />
    </span>
  </h3>
</template>
