<script lang="ts" setup>
defineProps<{
  /** Slug generated by @nuxt/content */
  id?: string;
}>();
</script>

<template>
  <h1 :id class="text-3xl font-bold">
    <!-- ARTICLE HEADER -->
    <slot />
  </h1>
</template>
