// shared folder is available to both server and app

/**
 * Timer Data (either total or challenge based) received from the frontend
 */
export interface TimerStatus {
  accumulatedSeconds: number;
  runningSince: string | Date | null;
}

/**
 * The **ONE** definition of elapsed time in this application.
 *
 * @param timer The currently active timer, either total or challenge.
 * @param now The timestamp generated by the user.
 *
 * @returns The total elapsed seconds for this timer as a number.
 */
export function elapsedSeconds(timer: TimerStatus, now: number): number {
  if (!timer.runningSince)
    return timer.accumulatedSeconds;

  const since = new Date(timer.runningSince).getTime();

  const current = Math.max(0, Math.floor((now - since) / 1000));

  return timer.accumulatedSeconds + current;
}

/**
 *
 * @param timer Timer data for a specific timer.
 * @returns Returns true if timer is running, false if it isn't.
 */
export function isRunning(timer: TimerStatus): boolean {
  return timer.runningSince !== null;
}
